<?php

function sub_nilai($nilai, $c)
{
    if ($c == "C1") {
        # code...
        if ($nilai == 90) {
            # code...
            $ket = "26 Hari";
        } elseif ($nilai == 80) {
            # code...
            $ket = "24 - 25 Hari";
        } elseif ($nilai == 70) {
            # code...
            $ket = "22 - 23 Hari";
        } elseif ($nilai == 60) {
            # code...
            $ket = "20 - 21 Hari";
        } elseif ($nilai == 50) {
            # code...
            $ket = "<= 19 Hari";
        } else {
            # code...
            $ket = "-";
        }
    } elseif ($c == "C2") {
        # code...
        if ($nilai == 90) {
            # code...
            $ket = "Hadir Tepat Waktu";
        } elseif ($nilai == 80) {
            # code...
            $ket = "1 - 59 Menit";
        } elseif ($nilai == 70) {
            # code...
            $ket = ">= 60 Menit";
        } else {
            # code...
            $ket = "-";
        }
    } elseif ($c == "C3") {
        # code...
        if ($nilai == 90) {
            # code...
            $ket = "Lebih Dari 10 Tahun";
        } elseif ($nilai == 80) {
            # code...
            $ket = "5 - 10 Tahun";
        } elseif ($nilai == 70) {
            # code...
            $ket = "Kecil Dari 5 Tahun";
        } else {
            # code...
            $ket = "-";
        }
    } elseif ($c == "C4") {
        # code...
        if ($nilai == 90) {
            # code...
            $ket = "Sangat Rapi";
        } elseif ($nilai == 80) {
            # code...
            $ket = "Rapi";
        } elseif ($nilai == 70) {
            # code...
            $ket = "Cukup Rapi";
        } elseif ($nilai == 60) {
            # code...
            $ket = "Kurang Rapi";
        } elseif ($nilai == 50) {
            # code...
            $ket = "Tidak Rapi";
        } else {
            # code...
            $ket = "-";
        }
    } elseif ($c == "C5") {
        # code...
        if ($nilai == 90) {
            # code...
            $ket = "Iya";
        } elseif ($nilai == 50) {
            # code...
            $ket = "Tidak";
        } else {
            # code...
            $ket = "-";
        }
    }

    return $ket;
}
